Vagrant.configure("2") do |config|
  config.vm.define "jenkins_server" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.network "forwarded_port", guest: 8080, host: 8080
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io docker-compose
      sudo systemctl start docker
      sudo systemctl enable docker

      wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
      sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      sudo apt-get update
      sudo apt-get install -y jenkins
      sudo systemctl start jenkins
      sudo systemctl enable jenkins
      sudo usermod -aG docker $USER
      sudo apt install openjdk-11-jre -y
    SHELL
  end

  config.vm.define "jenkins_worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.provision "shell", inline: <<-SHELL
      # Установка Docker
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl start docker
      sudo systemctl enable docker

      sudo apt-get install -y openjdk-11-jdk
      curl -O https://raw.githubusercontent.com/jenkinsci/master/jenkins.war
      java -jar jenkins.war --httpPort=8081 &
    SHELL
  end
end
